name: default
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        fail-fast: false
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set VCPKG_ROOT environment variable
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: |
          sudo apt-get install autoconf-archive
          sudo apt-get install freeglut3-dev
        shell: bash    

      - name: Set VCPKG_ROOT environment variable
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo $VCPKG_ROOT
          sudo vcpkg install --recurse
        shell: bash    

      - name: Set VCPKG_ROOT environment variable
        run: |
          cat /usr/local/share/vcpkg/buildtrees/skia/build-x64-linux-dbg-out.log
        shell: bash    
