name: default
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set VCPKG_ROOT environment variable
        run: |
          sudo apt-get install autoconf-archive
        shell: bash    

      - name: Set VCPKG_ROOT environment variable
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo $VCPKG_ROOT
          vcpkg install --recurse
        shell: bash    

