name: default
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Download sources
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: |
          sudo apt-get install autoconf-archive
          sudo apt-get install freeglut3-dev
        shell: bash

      - name: Install MacOS Dependencies
        if: ${{ matrix.environment == 'macos-latest' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install automake
          brew install autoconf-archive
        shell: bash    

      - name: Setup VCPKG
        continue-on-error: true
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        shell: bash    

      - name: Install VCPKG Dependencies (Linux + MacOS)
        if: ${{ matrix.environment != 'windows-latest' }}
        continue-on-error: true
        run: sudo vcpkg install --recurse
        shell: bash    

      - name: Install VCPKG Dependencies (Windows)
        if: ${{ matrix.environment == 'windows-latest' }}
        continue-on-error: true
        run: vcpkg install --recurse
        shell: bash    
