name: default
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Download sources
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: |
          sudo apt-get install autoconf-archive
          sudo apt-get install freeglut3-dev
        shell: bash

      - name: Install MacOS Dependencies
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install automake
        shell: bash    

      - name: Setup VCPKG + Install Dependencies
        continue-on-error: true
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          sudo vcpkg install --recurse
        shell: bash    

      - name: MacOS ICU errors
        if: ${{ matrix.environment == 'macos-latest' }}
        run: |
          cat /usr/local/share/vcpkg/buildtrees/icu/autoconf-x64-osx-err.log
        shell: bash    

      - name: Linux SKIA errors
        run: |
          cat /usr/local/share/vcpkg/buildtrees/skia/build-x64-linux-dbg-out.log
        shell: bash    
