name: default
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set VCPKG_ROOT environment variable
        run: |
          apt-get install autoconf-archive
        shell: bash    

      - name: Set VCPKG_ROOT environment variable
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo $VCPKG_ROOT
          vcpkg install --recurse
        shell: bash    

      - name: Set VCPKG_ROOT environment variable
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}
          mkdir logs
          cp /usr/local/share/vcpkg/buildtrees/icu/ logs -r
        shell: bash  

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Package
          path: |
            **/*.log
